#!D:/git/bin/sh.exe
./gradlew IncrementLint
status=$?
 echo "Task status:${status}"
if [ "${status}" == '0' ]; then
    echo "IncrementLint pass"
    exit 0
else
    echo "IncrementLint fail"
    exit 1
fi
